{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6891791"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.3.1.aar",
          "url": "navigation-runtime-2.3.1.aar",
          "size": 47202,
          "sha512": "f7a2e56724cb90ca42181e2f0eb2b842c9b0679728f7399a11b3744e1ce6ad67ad227777c24af69eb697ceb16a64a83df0c6a2ddcb110051f40f84d5d1763e9f",
          "sha256": "d8c9430f8a5200b8364d6d2d356c48e58d278a3d0df4f923371287eabc75cf14",
          "sha1": "1cb31e951e7e4b6de5e774bd20ef6c6a5719dc0b",
          "md5": "a868fda9c15ebf52309a0781c7a47a06"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.3.1.aar",
          "url": "navigation-runtime-2.3.1.aar",
          "size": 47202,
          "sha512": "f7a2e56724cb90ca42181e2f0eb2b842c9b0679728f7399a11b3744e1ce6ad67ad227777c24af69eb697ceb16a64a83df0c6a2ddcb110051f40f84d5d1763e9f",
          "sha256": "d8c9430f8a5200b8364d6d2d356c48e58d278a3d0df4f923371287eabc75cf14",
          "sha1": "1cb31e951e7e4b6de5e774bd20ef6c6a5719dc0b",
          "md5": "a868fda9c15ebf52309a0781c7a47a06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.3.1-sources.jar",
          "url": "navigation-runtime-2.3.1-sources.jar",
          "size": 34822,
          "sha512": "e5dfbdf0528aeaca22d1dff042f71ba8f939206dfb5ee3429f17d497507305032250ad18ec90e1fc8d102ccbd56218119b7a873dbdf6ca8a1e19178a1c8fd019",
          "sha256": "c686438fc9e9b5757a91ff6c29bd348914acc4f11379a1db81d68a03f86b4ab5",
          "sha1": "04b8041b3bde30ec200bcb9bafcee0c203b6f536",
          "md5": "f3d2184098d0667e5aa4aa0834666796"
        }
      ]
    }
  ]
}
