{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6891791"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.1.aar",
          "url": "navigation-runtime-ktx-2.3.1.aar",
          "size": 13227,
          "sha512": "40f9f2fc085142e7f8bd85ce88408abbb27946717b04ef3cabf9c599e8d6d5a3497c6bfdddeeef1aee9f6c846bb8f238ea8649c248ae0ad9833eb0c1bd13098c",
          "sha256": "65bdc23a7a39efa0a6eaa895dde50ed6aedede4b7bc50493bbe698f73549371d",
          "sha1": "fc2615c9e7d1a8d852d2f06e212f3916ac5da298",
          "md5": "afb3d72c9429fe0c5144a98cff2d5417"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.1.aar",
          "url": "navigation-runtime-ktx-2.3.1.aar",
          "size": 13227,
          "sha512": "40f9f2fc085142e7f8bd85ce88408abbb27946717b04ef3cabf9c599e8d6d5a3497c6bfdddeeef1aee9f6c846bb8f238ea8649c248ae0ad9833eb0c1bd13098c",
          "sha256": "65bdc23a7a39efa0a6eaa895dde50ed6aedede4b7bc50493bbe698f73549371d",
          "sha1": "fc2615c9e7d1a8d852d2f06e212f3916ac5da298",
          "md5": "afb3d72c9429fe0c5144a98cff2d5417"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.1-sources.jar",
          "url": "navigation-runtime-ktx-2.3.1-sources.jar",
          "size": 6128,
          "sha512": "f976814e20f825b4f16bf017c59918c3eb42304e8cb934b491431d2cf1e280bceea3a63b255a8ebbfcbb3886fdf26bd2a258e41928747b90eb04075e421ef4df",
          "sha256": "17df0a9cfd3b645ce58d9716f293ffdcfd8f30b60b87dab2a3cf099dddc1e70a",
          "sha1": "4d2da12a557444e5706dd6ca99f059ec099a45de",
          "md5": "fe0b36da8a72a76b3f3e34d30eebbcb2"
        }
      ]
    }
  ]
}
