{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common-ktx",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6891791"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.3.1.aar",
          "url": "navigation-common-ktx-2.3.1.aar",
          "size": 26400,
          "sha512": "f5bd8c1edc5b689f334d63366ddabaeace44d7c67925bea65350efee8fbc82ee3db960df0063d498353c3841fc6a98d65ec065f83b0853a8d21d8844d29508dc",
          "sha256": "6f0e2165dbe0da5b20e2aac94f9e19780d8dea3d66858864fdfb0fb1217816ff",
          "sha1": "8378dd50246bf646d37109e362acf1fdd0669fdf",
          "md5": "d51a25d0f39143f78810886ff270343b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.3.1.aar",
          "url": "navigation-common-ktx-2.3.1.aar",
          "size": 26400,
          "sha512": "f5bd8c1edc5b689f334d63366ddabaeace44d7c67925bea65350efee8fbc82ee3db960df0063d498353c3841fc6a98d65ec065f83b0853a8d21d8844d29508dc",
          "sha256": "6f0e2165dbe0da5b20e2aac94f9e19780d8dea3d66858864fdfb0fb1217816ff",
          "sha1": "8378dd50246bf646d37109e362acf1fdd0669fdf",
          "md5": "d51a25d0f39143f78810886ff270343b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-ktx-2.3.1-sources.jar",
          "url": "navigation-common-ktx-2.3.1-sources.jar",
          "size": 9270,
          "sha512": "2e660b763af1be2ce6c7a11a357707f4b2661e1d087d7cd0f5b7d3ea35d274ed1e7be631eef53f23c25dac96233c22a2b88f801d44d276d15f50fe873cc9f0bb",
          "sha256": "3785b406ae010b5b2080a61ac30f34473414c7b49bd07f0c0ade32ab204c931a",
          "sha1": "1a3ce7c2b9dcc97c1d25ef6ab8e016b5a76de983",
          "md5": "7a3b42155cd6aca62a286819294a8545"
        }
      ]
    }
  ]
}
