{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.gms",
    "module": "google-services",
    "version": "4.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6-rc-5",
      "buildId": "pxcffyovinaf7hqnmiagvomf34"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "google-services-4.3.4.jar",
          "url": "google-services-4.3.4.jar",
          "size": 38068,
          "sha512": "2a983653a83ec6312b6f2b671b7c9bb7ed9e3901b6d707e65860eabecacfc94cf5043822153b96005fb7df10725ffe0fb008b211c46e29c5456e2870bdda4aa4",
          "sha256": "ef9cb19e00d759a9754165e990e1146d9ec017bdacd399e28030c8b7bc86ffb5",
          "sha1": "47ac73f12375b90588fe92ce61d0979b409a3355",
          "md5": "44f07fd94cf42318ff8bc1cd393da20e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "strict-version-matcher-plugin",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.0.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "google-services-4.3.4.jar",
          "url": "google-services-4.3.4.jar",
          "size": 38068,
          "sha512": "2a983653a83ec6312b6f2b671b7c9bb7ed9e3901b6d707e65860eabecacfc94cf5043822153b96005fb7df10725ffe0fb008b211c46e29c5456e2870bdda4aa4",
          "sha256": "ef9cb19e00d759a9754165e990e1146d9ec017bdacd399e28030c8b7bc86ffb5",
          "sha1": "47ac73f12375b90588fe92ce61d0979b409a3355",
          "md5": "44f07fd94cf42318ff8bc1cd393da20e"
        }
      ]
    }
  ]
}
