{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6891791"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.1.aar",
          "url": "navigation-ui-ktx-2.3.1.aar",
          "size": 32272,
          "sha512": "2680253edbeefc3925a4fda7da848de1850e62adb82526b973d66a78231aa211504af46ddc29c5593daa641ca983ced15e7cc7aa7d205640079e447929d75a5e",
          "sha256": "62c3173fadbcb89f659531cab7f770662a30f583817e347a5971b273afc38f8a",
          "sha1": "b22d3339aeaaa01a640c7552238a224bf8aa1cd9",
          "md5": "0bcfeb1ca8def6cbd6419c9f07a682ea"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.1.aar",
          "url": "navigation-ui-ktx-2.3.1.aar",
          "size": 32272,
          "sha512": "2680253edbeefc3925a4fda7da848de1850e62adb82526b973d66a78231aa211504af46ddc29c5593daa641ca983ced15e7cc7aa7d205640079e447929d75a5e",
          "sha256": "62c3173fadbcb89f659531cab7f770662a30f583817e347a5971b273afc38f8a",
          "sha1": "b22d3339aeaaa01a640c7552238a224bf8aa1cd9",
          "md5": "0bcfeb1ca8def6cbd6419c9f07a682ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.1-sources.jar",
          "url": "navigation-ui-ktx-2.3.1-sources.jar",
          "size": 8751,
          "sha512": "0d56d35c76ca24964807607764080077f0d8ce960dc61e14629a2a1d50bd424ab455be041d64dc17edc52511c0db4d25c3e7b359a5bb44c9c37f2e0934ea1685",
          "sha256": "dc293a071dc2f04f69d456de6734531fa52ae69fecc83a4e1812006a3e5e3eae",
          "sha1": "407dd936012d5b65b0af3e897ea62e436a811419",
          "md5": "e5ff0652316f70fa6f7263ce5094a7ba"
        }
      ]
    }
  ]
}
