{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6891791"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.3.1.aar",
          "url": "navigation-fragment-2.3.1.aar",
          "size": 19314,
          "sha512": "7cc79a2690e24c40cc32e41d4ad748549cd77fc2bcfd97bd9723b622eacecdb363e24675790084ef602f25306a97d3b4abded901e2f49d23a5c721f05be6da52",
          "sha256": "9b0df1445451b3a15640b5b328ab29a0e77cb56d62ae865e81711833bcf3d6df",
          "sha1": "1f08259720089f6780ba6c0055ab113105efb631",
          "md5": "ba76b9f26d3274537b7e3328d99706a2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.3.1.aar",
          "url": "navigation-fragment-2.3.1.aar",
          "size": 19314,
          "sha512": "7cc79a2690e24c40cc32e41d4ad748549cd77fc2bcfd97bd9723b622eacecdb363e24675790084ef602f25306a97d3b4abded901e2f49d23a5c721f05be6da52",
          "sha256": "9b0df1445451b3a15640b5b328ab29a0e77cb56d62ae865e81711833bcf3d6df",
          "sha1": "1f08259720089f6780ba6c0055ab113105efb631",
          "md5": "ba76b9f26d3274537b7e3328d99706a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-fragment-2.3.1-sources.jar",
          "url": "navigation-fragment-2.3.1-sources.jar",
          "size": 13519,
          "sha512": "a7b754ab9cc7954d126ae2b30f905a6fd1c4ea9bbde736aee284820d4ab11e21a22026f78000ee5e59889f06cdf8a6fcb95512cb07fcf5df075b6522ed51c393",
          "sha256": "422448a3d055ce5eed89fdf46a035d5c3eedb9b6df061f4291cb81885cad6697",
          "sha1": "1b8d55b17ab1f3f2f7571e4882b6f90f58232022",
          "md5": "82cd3e6bb5536d33aa469ae592ffe060"
        }
      ]
    }
  ]
}
