{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6891791"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.3.1.aar",
          "url": "navigation-ui-2.3.1.aar",
          "size": 89974,
          "sha512": "483c52374f0ab89cfc837753772d29c69139c514410f2fab4a745ea76610bbcfec7b88accda994d04a2d280269f9048dc081ed7ff964ca5eb6cc383f4344a400",
          "sha256": "00db924d67f44a6b8b93144333d9c2a04c403563aeb117d4e8a22e6212a2f1ac",
          "sha1": "1fa82763861093405434da32d358c1d7c8fab464",
          "md5": "0363db6a7e846e7487040c4692a375ac"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.3.1.aar",
          "url": "navigation-ui-2.3.1.aar",
          "size": 89974,
          "sha512": "483c52374f0ab89cfc837753772d29c69139c514410f2fab4a745ea76610bbcfec7b88accda994d04a2d280269f9048dc081ed7ff964ca5eb6cc383f4344a400",
          "sha256": "00db924d67f44a6b8b93144333d9c2a04c403563aeb117d4e8a22e6212a2f1ac",
          "sha1": "1fa82763861093405434da32d358c1d7c8fab464",
          "md5": "0363db6a7e846e7487040c4692a375ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-2.3.1-sources.jar",
          "url": "navigation-ui-2.3.1-sources.jar",
          "size": 13609,
          "sha512": "2a1ca19a7bc9c98a77ff1c092ea9800aae070430414725e5dca0b8e03ea1142e7bae363b2d7f18be8e4d733adf86e353937bd791fbf7f39a971757c2cbec0cc7",
          "sha256": "1d489a864fd07c19a86093f4c0b3e179a217f4873599dda5e5dac1485f7cff5f",
          "sha1": "5c1143ec01dadc369c88ee30f21b49cec089b98a",
          "md5": "f2608f5303111ae7f8d93ea4d8054014"
        }
      ]
    }
  ]
}
