{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6891791"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.3.1.aar",
          "url": "navigation-common-2.3.1.aar",
          "size": 56588,
          "sha512": "26c0e53ad3534b5b47d6c0805e1b9507d25d9a60061e343d2077ad0ba17dc41472bcd03dca4a59ffcdcfe118b22ad4fcb6974e424ad6b47a9154fcad9752c3e9",
          "sha256": "86a6752b3bbd88f5bcd1f1a67a7bf2921e54fd667a03b2bf1f0b7d5a915ff118",
          "sha1": "75764941c5d5dd73813043dac3d3e6de7ce4d36a",
          "md5": "25369e4e54041f8ebb87a8f3930957c8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.3.1.aar",
          "url": "navigation-common-2.3.1.aar",
          "size": 56588,
          "sha512": "26c0e53ad3534b5b47d6c0805e1b9507d25d9a60061e343d2077ad0ba17dc41472bcd03dca4a59ffcdcfe118b22ad4fcb6974e424ad6b47a9154fcad9752c3e9",
          "sha256": "86a6752b3bbd88f5bcd1f1a67a7bf2921e54fd667a03b2bf1f0b7d5a915ff118",
          "sha1": "75764941c5d5dd73813043dac3d3e6de7ce4d36a",
          "md5": "25369e4e54041f8ebb87a8f3930957c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-2.3.1-sources.jar",
          "url": "navigation-common-2.3.1-sources.jar",
          "size": 35405,
          "sha512": "e0faad6704a73f6e10e7c42d28598b62684c73283f26832c31e13fa2aec378a73ccbf16e5a660b0765c2b6193a0a9cdb64517d59a7575203782fabcb90ef537e",
          "sha256": "0d7c07bfc40e6f4477472e54b0b86cfff675f0efd9f08d13282a7a7aabacf1d8",
          "sha1": "3b8f206a6105edba31131223dbc4ce128f44e543",
          "md5": "a1d71789a68690b467addea7567ded76"
        }
      ]
    }
  ]
}
