{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment-ktx",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6891791"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.3.1.aar",
          "url": "navigation-fragment-ktx-2.3.1.aar",
          "size": 17267,
          "sha512": "fe354340755f7d633cbef4e15e400f5533cf95106158157eb00626ce276e22d55f3b2feb224085d85550849a822e9748e18ec0acccc8a9a479925e7a1f81d4f2",
          "sha256": "cbe267d4f0f1b7c0d48b4dcb78c2d3e661e6f15bdc83e0a40e5900e4e88b574e",
          "sha1": "84fb46c253cb029a564dd1d198f4fd99b6d9f9e1",
          "md5": "06fe921e3a29e19510f24a507e98e793"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.3.1.aar",
          "url": "navigation-fragment-ktx-2.3.1.aar",
          "size": 17267,
          "sha512": "fe354340755f7d633cbef4e15e400f5533cf95106158157eb00626ce276e22d55f3b2feb224085d85550849a822e9748e18ec0acccc8a9a479925e7a1f81d4f2",
          "sha256": "cbe267d4f0f1b7c0d48b4dcb78c2d3e661e6f15bdc83e0a40e5900e4e88b574e",
          "sha1": "84fb46c253cb029a564dd1d198f4fd99b6d9f9e1",
          "md5": "06fe921e3a29e19510f24a507e98e793"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-fragment-ktx-2.3.1-sources.jar",
          "url": "navigation-fragment-ktx-2.3.1-sources.jar",
          "size": 6257,
          "sha512": "a6b68eb7fa8aeee59fc5e8e204415e67b286000163164b5b28d39e878870811987758b36cbff5b8f27a80cc5519f6312101e5c612853dc55d7134b0121bbd2b4",
          "sha256": "4cf53654f02d796c3ca1338f2c5c4a3d94045c524f6b88db150f3e218a64a914",
          "sha1": "9bebacd34921c1dd65c0cf5ceb32f70e8c7b17b9",
          "md5": "5473b099adf68016e77bd7472e687a4c"
        }
      ]
    }
  ]
}
